image: "juliacomputing/juliapro:v1.4.2-1"

variables:
  JULIA_PKG_SERVER: pumas.juliateam.io
  PRIVATE_REGISTRY_NAME: PumasRegistry
  PRIVATE_REGISTRY_UUID: 2207cf11-c0bb-4826-96c6-61cddfb0e7e8
  REMOVE_JULIAPRO: "true"
  # GitLab requires that the cache path is insde the project
  JULIA_DEPOT_PATH: "$CI_PROJECT_DIR/.julia/"

cache:
  paths:
    - .julia/compiled/

test:
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - >
      julia --color=yes --project=. -e
      'using Pkg;
       Pkg.instantiate();
       using PumasTutorials'
  artifacts:
    paths:
      - html
    expire_in: 1 week
  only:
  - master
  - tags
  - external
  - pushes

pages:
  stage: deploy
  script:
    - mkdir public/
    - cp docs/index.html public/
    - cp docs/resources.css public/
    - cp docs/CNAME public/
    - cp -r html public/
  artifacts:
    paths:
      - public
  only:
  - master
